# Generated by Django 3.0.4 on 2020-04-22 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent.Parent'),
        ),
    ]
